# ESP32 Firmware Verification Script
# Run this after uploading to verify the firmware is working

echo "=== ESP32 Firmware Verification ==="
echo "1. Check if ESP32 is connected to computer"
echo "2. Open Arduino IDE Serial Monitor (115200 baud)"
echo "3. ESP32 should show these messages:"
echo ""

echo "Expected Boot Messages:"
echo "-----------------------"
echo "[INFO] ESP32 Classroom Automation System Starting..."
echo "[INFO] Connecting to WiFi"
echo "[INFO] WiFi connected"
echo "[INFO] IP: 192.168.x.x"
echo "[WS] Initializing WebSocket connection"
echo "[HEALTH] Setup Complete"
echo "[INFO] Setup complete!"
echo ""

echo "Expected Runtime Messages:"
echo "--------------------------"
echo "[WS] Attempting WebSocket connection"
echo "[WS] WebSocket connected successfully"
echo "[WS] -> identify"
echo "[WS] <- identified"
echo "[HEALTH] Periodic - Heap: XXXX/XXXX KB"
echo "[WS] -> heartbeat"
echo ""

echo "=== Verification Checklist ==="
echo "☐ ESP32 powers on and shows boot messages"
echo "☐ WiFi connects successfully"
echo "☐ WebSocket connects to backend"
echo "☐ Receives 'identified' message from server"
echo "☐ Sends periodic heartbeats"
echo "☐ Memory usage stays stable"
echo "☐ No crash or restart messages"
echo ""

echo "=== Common Issues ==="
echo "• If WiFi fails: Check SSID/password in config.h"
echo "• If WebSocket fails: Check backend server IP/port"
echo "• If memory warnings: Monitor heap usage closely"
echo "• If crashes: Check serial logs for error details"
echo ""

echo "=== Next Steps ==="
echo "1. Test manual switches (if connected)"
echo "2. Test backend control via web interface"
echo "3. Monitor system stability over time"
echo "4. Check night time protection features"