# prometheus.yml
# Prometheus configuration for scraping Node.js metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: 'node-backend'
    static_configs:
      - targets: ['host.docker.internal:3001'] # Change to your backend metrics port if needed

  - job_name: 'mqtt-broker'
    static_configs:
      - targets: ['mosquitto:9001'] # If you expose MQTT metrics
